name: Distribution Workflow

on:
  workflow_dispatch:
  release:
    types: [published, released]

jobs:
  build:
    name: Distribute
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prepare Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements/build.txt
          python3 setup.py install

      - name: Distribute Package to PyPI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TWINE_PASSWORD: ${{ secrets.TWINE_TOKEN }}
          MASTODON_TOKEN: ${{ secrets.MASTODON_TOKEN }}
        run: inv distribute --tag v$(python setup.py --version 2> /dev/null) --no-dry-run
