name: Release Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prepare Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 

      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements/build.txt
          python3 setup.py install

      - name: Build Package
        run: inv build

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: inv release --no-dry-run

      - name: Distribute Package to PyPI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TWINE_PASSWORD: ${{ secrets.TWINE_TOKEN }}
        run: inv distribute
